import PDFDocument from 'pdfkit';
import { Response } from 'express';

interface ReportData {
  input: string;
  type: string;
  riskScore: number;
  riskLevel: string;
  summary: string;
  recommendations: string[];
  confidenceScore: number;
  createdAt: Date;
}

export function generatePDF(res: Response, report: ReportData): void {
  const doc = new PDFDocument({
    size: 'A4',
    margin: 50,
    info: {
      Title: `TrustLens Analysis Report - ${report.input}`,
      Author: 'TrustLens',
      Subject: 'Security Analysis Report',
      Keywords: 'security, analysis, trustlens, scam detection',
    },
  });

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename=trustlens-report-${Date.now()}.pdf`);

  doc.pipe(res);

  const primaryColor = '#2563EB';
  const textColor = '#0F172A';
  const secondaryColor = '#475569';

  doc.font('Helvetica-Bold').fontSize(24).fillColor(primaryColor)
    .text('TrustLens', 50, 50);
  doc.font('Helvetica').fontSize(10).fillColor(secondaryColor)
    .text('Security Analysis Report', 50, 80);
  doc.fontSize(9).fillColor(secondaryColor)
    .text(`Generated: ${new Date(report.createdAt).toLocaleString()}`, 50, 95);

  doc.moveTo(50, 115).lineTo(545, 115).strokeColor('#E2E8F0').stroke();

  doc.font('Helvetica-Bold').fontSize(16).fillColor(textColor)
    .text('Analysis Result', 50, 135);

  const riskColor = report.riskScore >= 80 ? '#16A34A' :
    report.riskScore >= 60 ? '#D97706' :
    report.riskScore >= 40 ? '#DC2626' : '#991B1B';

  doc.font('Helvetica-Bold').fontSize(12).fillColor(textColor)
    .text('Risk Score:', 50, 165);
  doc.font('Helvetica-Bold').fontSize(28).fillColor(riskColor)
    .text(`${report.riskScore}/100`, 50, 185);

  doc.font('Helvetica').fontSize(10).fillColor(textColor)
    .text(`Level: ${report.riskLevel.toUpperCase()}`, 50, 225)
    .text(`Confidence: ${report.confidenceScore}%`, 50, 240)
    .text(`Analyzed: ${report.input}`, 50, 255)
    .text(`Type: ${report.type}`, 50, 270);

  doc.moveTo(50, 290).lineTo(545, 290).strokeColor('#E2E8F0').stroke();

  doc.font('Helvetica-Bold').fontSize(14).fillColor(textColor)
    .text('Summary', 50, 310);
  doc.font('Helvetica').fontSize(10).fillColor(secondaryColor)
    .text(report.summary, 50, 335, { width: 495, align: 'left' });

  doc.moveTo(50, 400).lineTo(545, 400).strokeColor('#E2E8F0').stroke();

  doc.font('Helvetica-Bold').fontSize(14).fillColor(textColor)
    .text('Recommendations', 50, 420);

  let yPos = 445;
  report.recommendations.forEach((rec, i) => {
    doc.font('Helvetica').fontSize(10).fillColor(secondaryColor)
      .text(`${i + 1}. ${rec}`, 50, yPos, { width: 495 });
    yPos += 20;
  });

  doc.moveTo(50, yPos + 20).lineTo(545, yPos + 20).strokeColor('#E2E8F0').stroke();

  doc.font('Helvetica').fontSize(8).fillColor(secondaryColor)
    .text('This report is generated by TrustLens for informational purposes only.', 50, yPos + 40, { width: 495 })
    .text('Always exercise caution and use multiple sources when evaluating online threats.', 50, yPos + 55, { width: 495 })
    .text('© TrustLens - Know Before You Click', 50, yPos + 75);

  doc.end();
}
